## Importing numpy

In [1]:
import numpy as np

# 1-Arrays

### 1.1-Creating array

In [2]:
np1=np.array([1,2,3,4])
np1

array([1, 2, 3, 4])

In [3]:
type(np1)

numpy.ndarray

In [31]:
np.shape(np1)

(4,)

# 2-Matrix

### 2.21-Creating matrix using array

In [9]:
mat1=np.array([[1,2,3],['sam','jeba','raj']])
mat1

array([['1', '2', '3'],
       ['sam', 'jeba', 'raj']], dtype='<U11')

In [33]:
np.shape(mat1)

(2, 3)

### 2.22-Changing entry at a specific location of matrix

In [11]:
mat1[1,1]='zeon'
mat1

array([['1', '2', '3'],
       ['sam', 'zeon', 'raj']], dtype='<U11')

### 2.23- Arange-Linspace-Random


##### Arange-->arange() is an inbuilt numpy function that returns an ndarray object containing evenly spaced values within a defined interval.

In [13]:
# Note: It is arange and not arrange
mat2=np.arange(0,10,2)
mat2

array([0, 2, 4, 6, 8])

##### Random.rand- ->The numpy.random.rand() function creates an array of specified shape and fills it with random values

In [19]:
mat3=np.linspace(0,10,10)
mat3

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

##### Linspace-->linspace is an in-built function in Python's NumPy library. It is used to create an evenly spaced sequence in a specified interval.

In [34]:
mat4=np.random.rand(4,4)
mat4

array([[0.13865797, 0.23765469, 0.1159486 , 0.911489  ],
       [0.93256367, 0.94965655, 0.96554037, 0.40735604],
       [0.20425694, 0.52578008, 0.37794388, 0.40518845],
       [0.86076249, 0.71342445, 0.64516607, 0.46129092]])

In [35]:
mat4[0,1]

0.2376546882182763

In [36]:
mat4[2,0]

0.2042569390033715